### ISSUE TITLE
Info files

### ISSUE THREAD

**Issue by Razor1919** [Nova200019/ScrapperBack#1]
[From Datahut.pdf](https://github.com/Nova200019/ScrapperBack/files/14002925/From.Datahut.pdf)
[Portals and Terms _ Scheme Program.pdf](https://github.com/Nova200019/ScrapperBack/files/14002926/Portals.and.Terms._.Scheme.Program.pdf)
[Script_Webcrawler with comments.pdf](https://github.com/Nova200019/ScrapperBack/files/14002927/Script_Webcrawler.with.comments.pdf)
[Python Webscraping.pdf](https://github.com/Nova200019/ScrapperBack/files/14002928/Python.Webscraping.pdf)

**Comment by Nova200019** [comment]
👌👌
